# Generated by Django 5.0.3 on 2024-04-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAquaponie', '0002_rename_mesure_mesures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesures',
            name='humidite',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='dataHumidite'),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='lumiere',
            field=models.IntegerField(verbose_name='dataLumiere'),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='niveauDeau',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='dataNiveauDeau'),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='ph',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='dataPh'),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='temperature',
            field=models.DecimalField(decimal_places=5, max_digits=5, verbose_name='dataTemperature'),
        ),
    ]
