# Generated by Django 5.0.3 on 2024-04-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAquaponie', '0003_alter_mesures_humidite_alter_mesures_lumiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesures',
            name='humidite',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='lumiere',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='niveauDeau',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
