# Generated by Django 5.0.3 on 2024-04-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAquaponie', '0004_alter_mesures_humidite_alter_mesures_lumiere_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mesures',
            new_name='appAquaponie_mesures',
        ),
    ]
