# Generated by Django 5.0.3 on 2024-04-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAquaponie', '0005_rename_mesures_appaquaponie_mesures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appAquaponie_mesures',
            new_name='Mesures',
        ),
    ]
