# Generated by Django 5.0.3 on 2024-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAquaponie', '0006_rename_appaquaponie_mesures_mesures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesures',
            name='ph',
            field=models.DecimalField(decimal_places=100, max_digits=100),
        ),
    ]
