# Generated by Django 5.0.3 on 2024-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAquaponie', '0007_alter_mesures_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesures',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
