# Generated by Django 5.0.3 on 2024-05-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAquaponie', '0010_datafile_delete_cheatsheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesures',
            name='lumiere',
        ),
        migrations.RemoveField(
            model_name='mesures',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='mesures',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='mesures',
            name='humidite',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='mesures',
            name='niveauDeau',
            field=models.BooleanField(),
        ),
    ]
